version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: PyNEWS
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pynews
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount the init.sql file

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql
